Refactor OmegaId
vevcom/projectNext pull request #321
Opened 2024-09-13 17:23 UTC by theodorklauritzen

This reduces the size of the OmegaID QR code a lot. However the solution is maybe not that elegant.

2024-09-25 07:53 UTC, JohanHjelsethStorstad requested changes

2024-09-25 07:53 UTC, JohanHjelsethStorstad commented on src/services/omegaid/compression.ts
> +        console.error(e)
console.log

2024-09-25 07:53 UTC, JohanHjelsethStorstad commented on src/services/omegaid/compression.ts
> +
Maybe document the JWT -> QR compression on the top

2024-09-25 07:53 UTC, JohanHjelsethStorstad commented on src/jwt/parseJWTClient.ts
> -            typeof payload.usrnm === 'string' &&
I think this file is wrongly placed. First I think the function should be called parseJWTClient and this parse is specific to omegaId so why is it placed with the general jwt stuff. I think this should be split: one part is. in jwt libary it verifies and parses jwt on client. One part decodes and then uses this function - this should be placed with omegaId functionality.

2024-10-12 20:32 UTC, theodorklauritzen commented
Hmmm, the main branch had a bug with a circular dependency in Vevenadapter, this broke feide login in the development environment. The fix for now is to not use the method handler, this is against the convention, and we should maybe discuss a more permanent solution.

2024-11-07 19:10 UTC, closed without merging