Feat: Shop
vevcom/projectNext pull request #364
Opened 2024-11-22 21:31 UTC by theodorklauritzen

- Add Shop backend
- Admin page to administrate shops and products
- API to interact with shops
- A table that acts as receipts for product purchases.
- Connect student cards to users

Also see [API docs](https://github.com/vevcom/projectNext/wiki/API).

Remaining features:
- Connect to the money system
- Auth API KEY to only specific shops
- Visibility auth to how can edit shops, so users only can only access their shops
- Web shop
- OmegaID shop / Vandrebar

2025-01-12 22:56 UTC, Paulijuz requested changes
Looks awesome. The implementation of the shop looks nice. I added a few minor comments. There are a few major things however that will be necessary to change.

Firstly, I overhauled the ServiceMethod implementation to simplify some things. I would like to merge that PR (#381) before this. All calls to the "ServiceMethod" function will need to be changed. This should not take a lot of time, but I can help you with this if you want, just let me know.

Second, with the overhauled ServiceMethod I have a simple testing framework set in place. It'd be nice to write some tests for this feature. But, since it's not merged into main yet we can also do this in a later PR if you want.

2025-01-12 22:56 UTC, Paulijuz commented on src/services/shop/Authers.ts
> +export const ReadShops = RequirePermission.staticFields({ permission: 'SHOP_READ' })
Not directly related to your PR specifically, but should we create an auther for each service method, even if the requirements are exactly the same? This seems like a lot of work (repetition) for little benefit?

2025-01-12 22:56 UTC, Paulijuz commented on src/services/shop/product/update.ts
> +                        price: data.price,
If I remember correctly, the old vev stores the history of prices for a product. Not that it is necessary for our implementation, but it's something worth mentioning.

2025-01-12 22:56 UTC, Paulijuz commented on src/prisma/schema/user.prisma
> +model registerStudentCard {
Two small things.
1. I had to do a double take on what this model was intended for. Maybe a better name would help? Something like "StudentCardRegistrationQueue" or something along those lines.

2. UpperCamelCase is the convention for model names.

2025-01-12 22:57 UTC, Paulijuz commented
Also, great to see the wiki being updated!

2025-01-15 17:39 UTC, JohanHjelsethStorstad commented on src/services/shop/Authers.ts
> +export const ReadShops = RequirePermission.staticFields({ permission: 'SHOP_READ' })
I prefer it for splitting purposes. Since authers are both used in frontend and backend if one method changes its author it will be reflected on both frontend and backend checks

2025-01-15 17:41 UTC, JohanHjelsethStorstad commented on src/services/shop/Authers.ts
> +export const ReadShops = RequirePermission.staticFields({ permission: 'SHOP_READ' })
One auther for every service method that way a change will have no unintended side effects.

2025-01-15 17:42 UTC, JohanHjelsethStorstad commented on .eslintrc.json
> +            5
What was this changed for?

2025-01-15 17:44 UTC, JohanHjelsethStorstad commented on src/services/prismaCall.ts
> +
Thanks for finding this very bad bug after changing to ServiceMethods

2025-01-26 18:21 UTC, Paulijuz commented on src/app/admin/shop/[shop]/EditProductForShopForm.tsx
> +        ? updateProductForShopAction.bind(null, { shopId, productId: product.id })
with the new PR i created the utility functions `bindParams` and `bindData` for better readability

2025-01-26 18:27 UTC, Paulijuz approved these changes
Looks great!

Only two really minor things, but I have approved anyways as they are _really_ minor.

2025-01-26 18:27 UTC, Paulijuz commented on src/services/shop/authers.ts
> +// export const CreateProductForShop = RequirePermission.staticFields({ permission: ['PRODUCT_READ'] })
should this be uncommented?

2025-01-27 06:47 UTC, merged